-- Run this once in Supabase SQL Editor
create table if not exists public.household_people (
  id bigint generated by default as identity primary key,
  hh text not null,
  name text not null,
  nic text not null unique,
  created_at timestamptz not null default now()
);

alter table public.household_people enable row level security;

drop policy if exists "public read household people" on public.household_people;
create policy "public read household people"
on public.household_people for select
to anon, authenticated
using (true);

drop policy if exists "public insert household people" on public.household_people;
create policy "public insert household people"
on public.household_people for insert
to anon, authenticated
with check (true);

create index if not exists household_people_hh_idx on public.household_people(hh);
create index if not exists household_people_nic_idx on public.household_people(nic);

-- V34: make sure browser users can read and insert saved household members.
alter table public.household_people enable row level security;
drop policy if exists "public read household people" on public.household_people;
create policy "public read household people"
on public.household_people for select
to anon, authenticated
using (true);
drop policy if exists "public insert household people" on public.household_people;
create policy "public insert household people"
on public.household_people for insert
to anon, authenticated
with check (true);


-- Allow the browser management buttons to delete saved household records.
drop policy if exists "public delete household people" on public.household_people;
create policy "public delete household people"
on public.household_people for delete
to anon, authenticated
using (true);
